export const EVENT_SUBMIT = 'TAGS/EVENT_SUBMIT';
export const DELETE_TAG = 'TAGS/DELETE_TAG';
export const REQUEST_PHOTOS_BY_VALUE = 'PHOTOS/REQUEST_PHOTOS_BY_VALUE';
export const ASYNC_FETCH_PHOTOS = 'ASYNC_FETCH_PHOTOS';
export const ADD_PHOTO_TO_STORE = 'PHOTOS/ADD_PHOTO_TO_STORE';